### ISSUE TITLE
初次运行giachina时，报错'utf-8' codec can't decode

### ISSUE THREAD

**Issue by Dovahkiin9900** [infstellar/python-git-program-launcher#37]
操作系统：win10
安装路径：H:\Genshin_impact_assistant
安装版本：Release 2.2.1
解压完release后直接启动了launcher.exe，没有打开 clash/v2ray/其他加速器
在安装过程中：到了 _build PyQT5_ 这一步就会失败

![1698416021316](https://github.com/infstellar/python-git-program-launcher/assets/116942395/d39f0b27-c3d0-4105-9215-13e0b2e4769a)

**Comment by Dovahkiin9900** [comment]
对应日志：
2023-10-27 21:57:06.216 | TRACE    | pgpl.utils:run_command:195 - Building wheels for collected packages: PyQt5-sip
2023-10-27 21:57:06.218 | TRACE    | pgpl.utils:run_command:195 - Building wheel for PyQt5-sip (pyproject.toml): started
2023-10-27 21:57:08.337 | TRACE    | pgpl.utils:run_command:195 - Building wheel for PyQt5-sip (pyproject.toml): finished with status 'error'
2023-10-27 21:57:08.344 | TRACE    | pgpl.utils:run_command:195 - Failed to build PyQt5-sip
2023-10-27 21:57:09.441 | ERROR    | pgpl.pages:_start:196 - 'utf-8' codec can't decode byte 0xce in position 1020: invalid continuation byte
Traceback (most recent call last):

  File "H:\Genshin_impact_assistant\PGPL-2.2.0\toolkit\Lib\threading.py", line 890, in _bootstrap
    self._bootstrap_inner()
    │    └ <function Thread._bootstrap_inner at 0x000001EDBA8B3048>
    └ <Thread(Thread-5, started daemon 16164)>
  File "H:\Genshin_impact_assistant\PGPL-2.2.0\toolkit\Lib\threading.py", line 926, in _bootstrap_inner
    self.run()
    │    └ <function Thread.run at 0x000001EDBA8B1DC8>
    └ <Thread(Thread-5, started daemon 16164)>
  File "H:\Genshin_impact_assistant\PGPL-2.2.0\toolkit\Lib\threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
    │    │        │    │        │    └ {'callback': <function put_buttons.<locals>.click_callback at 0x000001EDBD13C558>}
    │    │        │    │        └ <Thread(Thread-5, started daemon 16164)>
    │    │        │    └ ()
    │    │        └ <Thread(Thread-5, started daemon 16164)>
    │    └ <function put_buttons.<locals>.click_callback at 0x000001EDCF26CD38>
    └ <Thread(Thread-5, started daemon 16164)>
  File "H:\Genshin_impact_assistant\PGPL-2.2.0\toolkit\lib\site-packages\pywebio\session\threadbased.py", line 261, in run
    callback(event['data'])
    │        └ {'event': 'callback', 'task_id': 'CB-click_callback-xflys9yRM9', 'data': 0}
    └ <function put_buttons.<locals>.click_callback at 0x000001EDBD13C558>
  File "H:\Genshin_impact_assistant\PGPL-2.2.0\toolkit\lib\site-packages\pywebio\output.py", line 839, in click_callback
    return onclick[btn_idx]()
           │       └ 0
           └ [<bound method MainPage._start of <pgpl.pages.MainPage object at 0x000001EDBD3E8748>>]

> File "H:\Genshin_impact_assistant\PGPL-2.2.0\pgpl\pages.py", line 156, in _start
    PipManager(launching_config, self.pt).pip_install(check_pip=check_pip, check_reqs=check_reqs)
    │          │                 │    │                         │                     └ True
    │          │                 │    │                         └ True
    │          │                 │    └ <pgpl.utils.ProgressTracker object at 0x000001EDBD3E8788>
    │          │                 └ <pgpl.pages.MainPage object at 0x000001EDBD3E8748>
    │          └ {'AutoUpdate': True, 'Branch': 'main', 'GitProxy': False, 'InstallDependencies': True, 'KeepLocalChanges': False, 'Main': 'ge...
    └ <class 'pgpl.managers.PipManager'>

  File "H:\Genshin_impact_assistant\PGPL-2.2.0\pgpl\managers.py", line 187, in pip_install
    self.execute(f'{self.pip()} install -r {self.requirements_file()}{self.pip_arg}')
    │    └ <function Command.execute at 0x000001EDBCF10E58>
    └ <pgpl.managers.PipManager object at 0x000001EDDC662DC8>

  File "H:\Genshin_impact_assistant\PGPL-2.2.0\pgpl\utils.py", line 277, in execute
    error_code, stdout, stderr = run_command(command, self.progress_tracker)
                                 │           │        │    └ <pgpl.utils.ProgressTracker object at 0x000001EDBD3E8788>
                                 │           │        └ <pgpl.managers.PipManager object at 0x000001EDDC662DC8>
                                 │           └ '"H:/Genshin_impact_assistant/PGPL-2.2.0/toolkit/python/3.7.6_GIA_Launcher_Download_Lib/python.exe" -m pip install -r require...
                                 └ <function run_command at 0x000001EDBCF06168>

  File "H:\Genshin_impact_assistant\PGPL-2.2.0\pgpl\utils.py", line 212, in run_command
    return rc, stdout.decode('utf-8'), stderr.decode('utf-8')
           │   │      │                │      └ <method 'decode' of 'bytes' objects>
           │   │      │                └ b'  error: subprocess-exited-with-error\r\n  \r\n  Building wheel for PyQt5-sip (pyproject.toml) did not run successfully.\r\...
           │   │      └ <method 'decode' of 'bytes' objects>
           │   └ b''
           └ 1

UnicodeDecodeError: 'utf-8' codec can't decode byte 0xce in position 1020: invalid continuation byte

**Comment by duguex** [comment]
By the way, the issue is different from #28, I suppose. The decode error is actually from "stderr.decode('utf-8')" as @Dovahkiin9900 post, and the stderr for me is list below:

  error: subprocess-exited-with-error
  
  Building wheel for PyQt5-sip (pyproject.toml) did not run successfully.
  exit code: 1
  
  [11 lines of output]
  running bdist_wheel
  running build
  running build_ext
  building 'PyQt5.sip' extension
  creating build
  creating build\temp.win-amd64-cpython-37
  creating build\temp.win-amd64-cpython-37\Release
  "C:\Program Files (x86)\Microsoft Visual Studio\2022\BuildTools\VC\Tools\MSVC\14.37.32822\bin\HostX86\x64\cl.exe" /c /nologo /O2 /W3 /GL /DNDEBUG /MD -IF:\PGPL-2.2.1\toolkit\python\3.7.6_GIA_Launcher_Download_Lib\include -IF:\PGPL-2.2.1\toolkit\python\3.7.6_GIA_Launcher_Download_Lib\Include "-IC:\Program Files (x86)\Microsoft Visual Studio\2022\BuildTools\VC\Tools\MSVC\14.37.32822\include" "-IC:\Program Files (x86)\Microsoft Visual Studio\2022\BuildTools\VC\Auxiliary\VS\include" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.22621.0\ucrt" "-IC:\Program Files (x86)\Windows Kits\10\\include\10.0.22621.0\\um" "-IC:\Program Files (x86)\Windows Kits\10\\include\10.0.22621.0\\shared" "-IC:\Program Files (x86)\Windows Kits\10\\include\10.0.22621.0\\winrt" "-IC:\Program Files (x86)\Windows Kits\10\\include\10.0.22621.0\\cppwinrt" /Tcapiversions.c /Fobuild\temp.win-amd64-cpython-37\Release\apiversions.obj
  apiversions.c
  apiversions.c(21): fatal error C1083: ÎÞ·¨´ò¿ª°üÀ¨ÎÄ¼þ: ¡°Python.h¡±: No such file or directory
  error: command 'C:\\Program Files (x86)\\Microsoft Visual Studio\\2022\\BuildTools\\VC\\Tools\\MSVC\\14.37.32822\\bin\\HostX86\\x64\\cl.exe' failed with exit code 2
  [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for PyQt5-sip
ERROR: Could not build wheels for PyQt5-sip, which is required to install pyproject.toml-based projects

**Comment by duguex** [comment]
I have solve this problem by adding a INCLUDE for python 3.7.6 to \toolkit\python\3.7.6_GIA_Launcher_Download_Lib. For me, the INCLUDE directory is generated by conda, and contains the "Python.h" header. @Dovahkiin9900

**Comment by JC-SCAU** [comment]
PGPL_2.2.0\toolkit\python\3.7.6_GIA_Launcher_Download_Lib目录下缺少文件
请手动在python官网安装3.7.6版本python 然后将Lib等文件夹复制到上述目录

**Comment by Marcus737** [comment]
> PGPL_2.2.0\toolkit\python\3.7.6_GIA_Launcher_Download_Lib目录下缺少文件 请手动在python官网安装3.7.6版本python 然后将Lib等文件夹复制到上述目录 如图所示 ![image](https://user-images.githubusercontent.com/52768713/280511525-e601ee98-831c-492c-bb29-843a6050c3a6.png)

有用，只需要include文件和libs文件夹，python下载可以https://mirrors.huaweicloud.com/python/这里下

**Comment by Dovahkiin9900** [comment]
谢谢♪(･ω･)ﾉ
Thanks!
